### ISSUE TITLE
Add env SENTINEL_PASSWORD_FILE

### ISSUE THREAD

**Issue by Tobjoern** [leominov/redis_sentinel_exporter#12]
Docker swarm uses secrets, which are stored in a in-memory file (e.g. /run/secrets/password).
People using docker swarm have to create a wrapper image for the redis-exporter.
It would be more convenient to have the environment variable SENTINEL_PASSWORD_FILE, which would be an alternative to SENTINEL_PASSWORD, and would try to read the passed-in file for the sentinel password.
This environment variable would be very easy to implement, as it would only require a simple file read, but would save many people time.

What do you think about this?

**Comment by leominov** [comment]
https://github.com/leominov/redis_sentinel_exporter/releases/tag/v1.7.0

**Comment by Tobjoern** [comment]
Thanks for the quick help :+1:
