### ISSUE TITLE
Rename redis_sentinel_build_info to redis_sentinel_exporter_build_info

### ISSUE THREAD

**Issue by perlun** [leominov/redis_sentinel_exporter#14]
Hi,

Thanks for a nice piece of art. :+1: After deploying this to a test cluster of mine, I noted that this metric is perhaps slightly misnamed:

```prometheus
# HELP redis_sentinel_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which redis_sentinel was built.
# TYPE redis_sentinel_build_info gauge
redis_sentinel_build_info{branch="feature/issue-12",goversion="go1.14.9",revision="bc6f9afd76cbe378b401ddcad535cc7384dc3aec",version="1.7.0"} 1
```

By comparison, this metric (which also provides metadata about the `redis_sentinel_exporter` itself) has a much more rational name:

```prometheus
# HELP redis_sentinel_exporter_last_scrape_duration_seconds The last scrape duration.
# TYPE redis_sentinel_exporter_last_scrape_duration_seconds gauge
redis_sentinel_exporter_last_scrape_duration_seconds 0.000765489
```

### The problem

The existing name is far too similar to the `redis_sentinel_info` metric, IMHO. I looked briefly in the source code (was initially intending to throw in a PR right away), but couldn't find it and it perhaps doesn't hurt to discuss it briefly first anyway.

(If you agree that this should be fixed and want to do the renaming yourself, I surely won't mind either.)

```prometheus
# HELP redis_sentinel_info Information about Sentinel
# TYPE redis_sentinel_info gauge
redis_sentinel_info{build_id="636cde3b5c7a3923",mode="sentinel",version="5.0.7"} 1
```

**Comment by leominov** [comment]
Sounds reasonable :)

**Comment by perlun** [comment]
:+1: Where is this in the code btw?

**Comment by leominov** [comment]
@perlun check 1.7.1 release

**Comment by perlun** [comment]
> @perlun check 1.7.1 release (binaries or docker image)

Thanks, looks nice! :smile: (Haven't tested the version yet, just looked at the PR.)

**Comment by leominov** [comment]
So... open new issue in case of problem with this
