### ISSUE TITLE
Docker Images

### ISSUE THREAD

**Issue by phal0r** [leominov/redis_sentinel_exporter#3]
Hi @leominov ,

thanks for this project. This is what I am currently looking for. I want to use it in a dockerized environment. Are ready to use images provided somewhere or do I need to build them on my own?

Update: I have set up a CI build for this project under https://github.com/atroo/redis_sentinel_exporter to get things started. If you are not ok with this approach, just let me know.

**Comment by leominov** [comment]
Hello, @phal0r. Sorry for the delayed response. Looks like it can be done without travis-ci by connecting repo with hub-docker.

https://hub.docker.com/r/leominov/redis_sentinel_exporter
