### ISSUE TITLE
Support for Environment Variables

### ISSUE THREAD

**Issue by alexswilliams** [leominov/redis_sentinel_exporter#8]
Hi,

This looks fab - but to be useful for me it would need to support setting config through environment variables as well as commandline flags (e.g. to facilitate injecting secrets in kubernetes.)

If you think this is an OK idea but don't have the time or capacity to add this then I'm more than happy to have a go and submit a PR :)

Alex

**Comment by leominov** [comment]
Hello, Alex

Check 1.5.0 version

**Comment by alexswilliams** [comment]
Oh wow- yes, that's perfect, thank you very much :)

Alex
